name: Variables de Ambiente predeterminadas

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Mostrar valores de variables de ambiente
      run: echo $GITHUB_ACTION &&
           echo $GITHUB_EVENT_NAME &&
           echo $GITHUB_REPOSITORY &&
           echo $GITHUB_RUN_NUMBER &&
           echo $GITHUB_WORKFLOW &i&
           echo $GITHUB_WORKSPACE &&
           echo $RUNNER_NAME &&
           echo $RUNNER_OS &&
           echo $RUNNER_ARCH
